jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: nPeolwZ2indJR3nThfpFiWlL+Etwd3x1IfkogquXyWbPgyW28i2PVRdW64oyHOaIZjYbJvajcMDSqLWkX8vnzqL5iHw3BeRYxE/qahChRsFzzPShCAvCkblsKyaqN+klOYfpe/hNZaN7XdjnKsS4YorLlt42i+GxLXJWGdnxkE0/gcAd+k9gYOEAcsLD9fCzx5AqJfB7nQ0csszeTK9G9FwgBllsEO7lRtmRlD4hlxei6hXzOI/BJqf12+4edWLP/WTv7ZGH2aek5IkNhfs6JA+p6lRN0npR4GMgce352JNjJD7pcnrKhm+A78H7/bVFUJahbnvHYWs8NIiRH/Q061oq1RmUucyG75sbX2V531q6k+tS8AKcPROuVPc137ZycD4rZJ1ouq6ISV2S7/PfVjRBPeL43v16WRkCkpyAt78/o5Gj+B470a199YQ8RwoIWhPOP0OAiNGQqqthUc45tZ35Qs20gchZ0T7EjtgbflMbCvrSRUdIhXF+4dYAFCbo3/gzmZETgk9Svbkfhnsr4Lgc4tsgF2r3EjiTzOodwUqFZFKNw/d+MUa/vS8IHbI70d//dP5J9RMtCLJu/dxntyEXzzBId7gXCDIHfI2hmM0M2DKU/jrQ34ZdtpShxZbU2qngy6vDcFQFkaXMgU56sJT2CeSWrIyYieW2/rqnRXc=
  app: italkiclone
  on: main
