jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "aaeKLpZUC4+Clijfq6Da8JvbxoFjcQGSh+AU9eSYoorrGsY35/eecMNfH/dolIKGYbA56Qd27PtDcw35piKCGM2sHNbt/KySrAtqRWaBmiYJCLf1K2LQWX/HsZE2ByMYXIyhZXm1RYfIzRgUM+iIBkdTPwlgf/W/0QRHih1C1zqYNtTYxwHzpnnL3zaxu4o/3pOFviifYdXERGk+LyxNhRpqy3NFNMQg9QK1dJFKBYEduvoMHv5hjngd9I+i9y49eIejnJSBpw+KpWssHzTV65oe0eC+2GccD0NMCbhpsAZVDKREAQuY0lImN6CM4re/r9pkHsz5GHAdvbKf9MN6sK4eG90icKEshSj72XFGCHRUYz8Lw31g6SyOm0GdaQHj/k0aDp8o0AFmDnm/E9McDJ+zTQjZq1h+G+VYu19AbmSBlTkziunxiXiRjj+UGk5bGvjeFIFuBAE1LGW8MYq6GRrqgdISAA5B/V49i5pa1nqZc3XUmMKwVKnD836ExlnqprbGXfpOZTjsEImIXdTrd+06AZlzzLItq1PJuZwaFIyMS5XVSARgDmwk9nBHQH0fAICEb/47rW16j0/wX/rcr6KgQZghzsoI7+/Y1VlZ9EA6zBzo2W1t/8GhvYHyVuYU+Y7mX06pTjRzS91wWMnEtB1RcSua8Yy7RnTqhPTe6PM="
        app: languagelearningplatform
      on: main