jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "RO3MJ803adCx8S1AOt81WHl7B/wRI78htUrZt3cWKbOU8YZqqhR2R1rs8QHGJNQkFY/K1q3Pg6hBCYOP+GxZ+9CpBjL2W3SGear4Q+9DdccbcZV8iortOqj604XlIaGtD73uFPJYIKDBT7/roGpKP1VnmBOoYTcnofDcw9smKlDHLWi3O2L3XN565Cfzk8f7bunhZdUzDov8xvS5v0fmNVC2o17ipr2xY/WdfHVuQEuJcJsclangJmowqrvxmoxGWy6dqVhXftD+ZVXm6a07lc0i6KuiPUqmKpKD0uj/ymwvLOfHYTDgCdfZM/fWcpUCW7HTFfwoqw4IpEVOQAkkny6Lo/7ZE7hfDmLq4QO23XAzNwiCkJNO3/6EKBb/GnQKv2civpHpNzgHFcxkuN9OYRyyZbh+5fC9pezJTZBIFaOA2q40WAwJnIVVUVV0JgGJxEx6DUKB0d54enJCwCyL7aOZ8K5Zx51d4PV0smoBNj2dtPh79YL1GflkgrXLpnfN8Am5LkW5Jrs0QyKxXIVLqI5FaShUT4UBvP/5FWTVhPlXeyAt9eRdCTe2qqUS6KBMLAb0I1DxgsPNJJswCwDQxQgkItzIS1kcvZsRM+jbH6thNaTppqp7e5XCn81cxgfgQl832hlJFtsDr1wC+MVscbLbVCPUfM3/85jKDQeDhxw="
        app: languagelearningplatform
      on: main