jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: CeYFfG0bHXt4MsRngpmlml1Laciqqo80d5twiNirVEeZwtbyO2DRScf+O0Z5Bx0On1o8/NwA3vgH5PQOw+dpqePu+m6Z2bEryO4uTUtm06Z1Ze8p6bjcrN6/6yu4tQJC2eOkH2olFzOuW9fti0n8g7NDf1u1HR8vRJA9rL05rbMDl57nlH2I2ttitwtTyg5MfSe8T5n6gfGmB2ijtmUxWJkxo7mUpP7ySJ6kep4fE6DS8vA4IolBPKQqTjsrxGFGy94bUDI2tkFLa8gDvn0hVsN1JQGNlhvRg3/BY6AMqbo322vgkyskmLSmPNtqB2iNn+v6bl03qEQvK70KvXRx+mv4frjV2o7djtWK4xR1z1gKluu0rnsb4WB8PsHd2ip03DgFGlmk8feSbn2Y64E+JI3eC/iEqnsrTsWe07P3acQQrchXZkee02E0GRlLUD8iwBWfDRyrZng8TjVXWDXxkETZTUOs5nvSccRwPI+ab1SA36ad3lovD8woIOrbmZ7w2DT/0AHjgQtLXqqcpCzlyCYpZsxdkl4rE1YkHFbjHxYdQUZWXbCzwpD3BaEY83MmuhH3pvA9Hnw4w6Rg/T63ElrhzYJSmUdTl3obaEhHCYycfzXHgjLwtNft0Lygii+hQsER/o9T5DEHje7rwCS3XYPMBzFk9QGH7hP4dIm3GXY=
        app: italkiclone
      on: main