jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "D2wzoTKhX1cPvRKl8D6w4RQoguVVmoOSk5YZIsw+kRY0WWwTg1TVc/AsSqsU5wUgb2uvmxXZbI2ER5N1Q1+cS68YeHj6lQe/JFeFITxT5RUSKm8l9Tr0cyaKi1+bU5Tw2nhM1LM6uEWKBaJXmhxJ4jDGKyf3zH9BgTg1kVHnPDSr3a4iWLnEj8WqXOOvpyiXPS0gnktIDMmNe38A6/s6L+kYSMBI7QBXbKQl5merzq3ru/DM8KdE1EdPx8ubAHvDfUBAF0zoF0VOqujmkI8xsIgqBdORThG8+GuY1f2JgnKn2D8H+4GCx30G2TyEvypK9iAp7sjmK+W2MfppcuWi7xsG+m2Tx+ZMdDfcUth07jugUSQk1SQOpehSBqsG2tSecBmuJbEjFHTv0UwCa3dfvX+78cy8PBuGNS/vnnKp6saIwlzxETi5gzEahGCJqv0z+ZhTQcZ8TqEO3tqfw894BcfElEzRGS6aXJ4qFZQrDUOLlSvRBqnkds/rnmZYan6ucePOLFKtnW27bqzZw+6JLChmmdmhu0vVm2RUmxTh9zO0EV3y3vGoht6072DjD7bw4Egx21P5mSwnLIJ7yvJhjiTffEzT76ZCbhZeJRM+kmD7qV7zZ4N5bAE2hCykhNoU/WESFfFS553AyjHlnbaCrbUb85pS281qLxM3x5yGffo="
        app: languagelearningplatform
      on: main