jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "LXNXAoUMbJgmFzhd5D2B5mhMLDoQBJdfDy33Y+QjyGpm3EFttpMT9OVCbZpPenll61vCcXSlYXh4Z7Hf3lbwR8VzZo77bVQUgoX537XS4cgvcciySuyTCjKnWkKFLk0HuEV9Jv82fb7l/pHzMLdv8yIf2XUXZMz5bqHRGfIw0NVNyBVOHAoA0WWxQT+YLzwsA2EpaZm3JyjPg/LiNCP/94BY9TUBTaQUus/jbNBAML1tHmSiDpFeEHWTP0OlCSEOI5+C105YhbMeFkxJ4Ywu5X/fRCLYNUNimTVDoRj++5VHvK/DpcWjqiEU+BEekDRmVuuXKey3+mid7gH6tczhrQ6ZFigihuhX/Ud8Yu54VZi5buob4hXAJEvWvTBa2Z/gE2ZkonflXqKtGZYRHOQdZSyvnWrpYd1ORDLFH9g6/WjqtaiP6MMKvuWvROKEuEiHgAqA3hrhM4OokIsuDPKwlbed1KnacqjX0WiYyJoNJxEynH4FBh6GSmSUoRuo4GgS0yJO3cd5b+EkEx/uAuUZO75Xow8nkTKo8/GTXchcAT4XxCfQQzY/TZXcg6aIkjjCtacljehl8F5LiVIxzT6fQT8OIwk0gWj7mZuqGxkm2+zzy6O/oIx/3NAuWlLz259PMk5rO493YMRL01ROttKs/6xoEvbR04hi2Q11o7KcGCg="
        app: languagelearningplatform
      on: main