jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: SH9YRUi5UywJZQv5u+cZEv+PDruc8R0wI5XY5qTU4cLHy3GK2Ta4W78x2vgOHsPtJMSaiU36W42MPe9peWr5vgIa6sA6BPsmFwEtVIgDBlpkdixRpi9mLhg8kt/PCzrDBTx4PLSTKpM5J0aIupzxWivywjXbsara1/2gnilwVM6cXEwjQ2km1ynYZDEcD+rTKSwBfObwMwPg+udwoaAzqnS2SRlULBu8AvSYEG1OZ6T/DH2HiGHMpLUl39JBHt64IVHVJsoWN159W5SFU4s76O8dF2MbGF/11o2UFYT//6njDainuLfG2oHpJ7Qov2VuQcbt6ahPIHR+PFthrPqB4HAiaIcnk4JLjQSgW3dugE7AQZj0IDGM0UXKSrypBEwJr+66r1S3hCwSjAovOoycFCvL012jCU6ZYUT/jlZU7Ae/GAtKTuQOtTptaH2p20eHDTyrtC2SE/4o6QCXeRjdH/PclHX9C9AqunSOeWb8lEXFK/bG4GQ/C0vRNXuwvHVG4LpqteNQ0cj/WJlU7j2AQq3frAiSE+vR7mwK/vLxe7r07jPmRCsmnswOLawNvGYTjbHLE2fqpyLSUOhsP0zOGAmWfCunv2SnICMd161Om6XV03FmBhFIgvR+ye5yM9/Gor2+7O31601wcQ5DhRDGouhWZdolkWXKCf0ByJccQa4=
        app: italkiclone
      on: main