jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "D61kHcKXlJSdeRJmM5HZLeRr4Yzi2KUJKLlaL18x/PkzxBCTGRvy21i7gStlj/H+rjyNtLtEsGKdKDaNiAhLWnbneN7UzmkVFm+9UsDc8rjCM6MoNdNeQMOfDw7zQw0xK2pgM1XtfxkRgWawQcBGVNdA0eZM3jNE6mQiWQfkzbmnDKORGN+qdKacMW/DtJjosVIndWJ79u9iWi9zGe+3Bap/cAwmuK6KQXJiKe5Tl21taaVt0b7E3CSjvobhBll58ugb0SwDNqTluedaGxicB79qZ1fo7UsPzls0rCVLimavFPGa3j9P2XP2OKyQld/tLcCiyMgKGuyjcIwvJmDRjDvEktcaK4eKgGsR7QfoB65Tu/fi486n++AG2hr3dfes9jfFRV4rBCqAAlhB3pTECLQZe955X3OWaXgKUKSyTH71VZKhFd8/G/tAfCu3gTeeNHJKcs/3GYA78tCHsxE2Aja8MDu7h/rmwcBvGr0xf7JOFmex6MUOcCAxjYrZqnO8IVXDJQLAGHvDLC7CRA4qHSH6E+HBKo30RoRFL0PubQBhN6d7YjW30fEfh5RNZ3H81uN+PUm3Y8BZUlHYkLkXv/Pw/VbM+uO60QAXgfp+9j3N5nOS9wqn/NG8G+xL5OygCbYdDcxreLak3d39X+QIwqPQhb0jdliUAhl6KO00Pa4="
  app: italkiclone
  on: main
